#general variables
    #strLAB_1
    10.37.129.18
    #strLAB_2
    10.37.129.16
    #strUBUNTU
    10.37.129.17
   #strLAB_1_name
    LAB-1
   #trLAB_2_name
    LAB-2
   #strUBUNTU_name
     UBUNTU
    #strSQL_SVR_name
     MSSQL Server 2005
#windows
    #strWIN_USER
    user
    #strWIN_PASSW
     pass
#ftp server
    #strFTP_IP
    10.37.129.18
    #intFTP_PORT
    21
    #strFTP_USER
    ftpUser
    #strFTP_PASS
    ftpPass
#mssql server
    #strSQL_USER
     sa
    #strSQL_PASS
    SYSADM
    #strSQL_IP
    10.37.129.16
    #intSQL_PORT
    1035
#plink
    #strTARGET_IP_3389
     127.0.0.1
    #strTARGET_IP_445
    127.0.0.1
